
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

sources :
  - name : dwh_raw
    tables :
      - name : address
      - name : countryregion
      - name : creditcard
      - name : customer
      - name : date
      - name : person
      - name : product
      - name : productcategory
      - name : productsubcategory
      - name : salesorderdetail
      - name : salesorderheader
      - name : salesorderheadersalesreason
      - name : salesreason
      - name : stateprovince
      - name : store